### ISSUE TITLE
Support for 1.11.2 ?

### ISSUE THREAD

**Issue by deltaflyer4747** [megoesrawr/LWCEntityLocking#18]
Hello, just tried to launch ELWC on 11.2 but failed miserably. Could this be fixed? I was not able to launch it on 1.11 either...

`[09:17:52 INFO]: This server is running CraftBukkit version git-Spigot-7d78b81-0fb3f8b (MC: 1.11.2) (Implementing API version 1.11.2-R0.1-SNAPSHOT)`

```
[09:17:20 ERROR]: Could not load 'plugins/EntityLWC.jar' in folder 'plugins'
org.bukkit.plugin.InvalidPluginException: java.lang.UnsupportedClassVersionError: com/griefcraft/lwc/LWCPlugin : Unsupported major.minor version 52.0
        at org.bukkit.plugin.java.JavaPluginLoader.loadPlugin(JavaPluginLoader.java:133) ~[spigot-1.11.2.jar:git-Spigot-7d78b81-0fb3f8b]
        at org.bukkit.plugin.SimplePluginManager.loadPlugin(SimplePluginManager.java:329) ~[spigot-1.11.2.jar:git-Spigot-7d78b81-0fb3f8b]
        at org.bukkit.plugin.SimplePluginManager.loadPlugins(SimplePluginManager.java:251) [spigot-1.11.2.jar:git-Spigot-7d78b81-0fb3f8b]
        at org.bukkit.craftbukkit.v1_11_R1.CraftServer.loadPlugins(CraftServer.java:300) [spigot-1.11.2.jar:git-Spigot-7d78b81-0fb3f8b]
        at net.minecraft.server.v1_11_R1.DedicatedServer.init(DedicatedServer.java:204) [spigot-1.11.2.jar:git-Spigot-7d78b81-0fb3f8b]
        at net.minecraft.server.v1_11_R1.MinecraftServer.run(MinecraftServer.java:542) [spigot-1.11.2.jar:git-Spigot-7d78b81-0fb3f8b]
        at java.lang.Thread.run(Thread.java:745) [?:1.7.0_111]
Caused by: java.lang.UnsupportedClassVersionError: com/griefcraft/lwc/LWCPlugin : Unsupported major.minor version 52.0
        at java.lang.ClassLoader.defineClass1(Native Method) ~[?:1.7.0_111]
        at java.lang.ClassLoader.defineClass(ClassLoader.java:803) ~[?:1.7.0_111]
        at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142) ~[?:1.7.0_111]
        at java.net.URLClassLoader.defineClass(URLClassLoader.java:449) ~[?:1.7.0_111]
        at java.net.URLClassLoader.access$100(URLClassLoader.java:71) ~[?:1.7.0_111]
        at java.net.URLClassLoader$1.run(URLClassLoader.java:361) ~[?:1.7.0_111]
        at java.net.URLClassLoader$1.run(URLClassLoader.java:355) ~[?:1.7.0_111]
        at java.security.AccessController.doPrivileged(Native Method) ~[?:1.7.0_111]
        at java.net.URLClassLoader.findClass(URLClassLoader.java:354) ~[?:1.7.0_111]
        at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:101) ~[spigot-1.11.2.jar:git-Spigot-7d78b81-0fb3f8b]
        at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:86) ~[spigot-1.11.2.jar:git-Spigot-7d78b81-0fb3f8b]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:425) ~[?:1.7.0_111]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:358) ~[?:1.7.0_111]
        at java.lang.Class.forName0(Native Method) ~[?:1.7.0_111]
        at java.lang.Class.forName(Class.java:278) ~[?:1.7.0_111]
        at org.bukkit.plugin.java.PluginClassLoader.<init>(PluginClassLoader.java:64) ~[spigot-1.11.2.jar:git-Spigot-7d78b81-0fb3f8b]
        at org.bukkit.plugin.java.JavaPluginLoader.loadPlugin(JavaPluginLoader.java:129) ~[spigot-1.11.2.jar:git-Spigot-7d78b81-0fb3f8b]
        ... 6 more
```

**Comment by deltaflyer4747** [comment]
Ignore this issue, my bad, it was caused by old java (1.7) as only 1.8 is supported now.
