### ISSUE TITLE
Verson 1.8.7 Errors on purge!

### ISSUE THREAD

**Issue by ScuroK** [megoesrawr/LWCEntityLocking#34]
I get tons of error on /lwc admin purge <name>

[15:05:36] [Server thread/ERROR]: null
org.bukkit.command.CommandException: Unhandled exception executing command 'lwc' in plugin LWC v1.8.7
	at org.bukkit.command.PluginCommand.execute(PluginCommand.java:46) ~[craftbukkit.jar:git-Spigot-65e8124-bde2a93]
	at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:141) ~[craftbukkit.jar:git-Spigot-65e8124-bde2a93]
	at org.bukkit.craftbukkit.v1_12_R1.CraftServer.dispatchCommand(CraftServer.java:647) ~[craftbukkit.jar:git-Spigot-65e8124-bde2a93]
	at net.minecraft.server.v1_12_R1.PlayerConnection.handleCommand(PlayerConnection.java:1386) [craftbukkit.jar:git-Spigot-65e8124-bde2a93]
	at net.minecraft.server.v1_12_R1.PlayerConnection.a(PlayerConnection.java:1221) [craftbukkit.jar:git-Spigot-65e8124-bde2a93]
	at net.minecraft.server.v1_12_R1.PacketPlayInChat.a(PacketPlayInChat.java:45) [craftbukkit.jar:git-Spigot-65e8124-bde2a93]
	at net.minecraft.server.v1_12_R1.PacketPlayInChat.a(PacketPlayInChat.java:1) [craftbukkit.jar:git-Spigot-65e8124-bde2a93]
	at net.minecraft.server.v1_12_R1.PlayerConnectionUtils$1.run(SourceFile:13) [craftbukkit.jar:git-Spigot-65e8124-bde2a93]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_101]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_101]
	at net.minecraft.server.v1_12_R1.SystemUtils.a(SourceFile:46) [craftbukkit.jar:git-Spigot-65e8124-bde2a93]
	at net.minecraft.server.v1_12_R1.MinecraftServer.D(MinecraftServer.java:748) [craftbukkit.jar:git-Spigot-65e8124-bde2a93]
	at net.minecraft.server.v1_12_R1.DedicatedServer.D(DedicatedServer.java:406) [craftbukkit.jar:git-Spigot-65e8124-bde2a93]
	at net.minecraft.server.v1_12_R1.MinecraftServer.C(MinecraftServer.java:679) [craftbukkit.jar:git-Spigot-65e8124-bde2a93]
	at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:577) [craftbukkit.jar:git-Spigot-65e8124-bde2a93]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_101]
Caused by: com.griefcraft.scripting.ModuleException: LWC Module threw an uncaught exception! LWC version: 1.8.7
	at com.griefcraft.scripting.ModuleLoader.dispatchEvent(ModuleLoader.java:394) ~[?:?]
	at com.griefcraft.lwc.LWCPlugin.onCommand(LWCPlugin.java:175) ~[?:?]
	at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44) ~[craftbukkit.jar:git-Spigot-65e8124-bde2a93]
	... 15 more
Caused by: com.griefcraft.scripting.ModuleException: java.sql.SQLException: No operations allowed after statement closed.
	at com.griefcraft.sql.Database.printException(Database.java:196) ~[?:?]
	at com.griefcraft.sql.PhysDB.precache(PhysDB.java:919) ~[?:?]
	at com.griefcraft.modules.admin.AdminPurge.onCommand(AdminPurge.java:77) ~[?:?]
	at com.griefcraft.scripting.ModuleLoader.dispatchEvent(ModuleLoader.java:370) ~[?:?]
	at com.griefcraft.lwc.LWCPlugin.onCommand(LWCPlugin.java:175) ~[?:?]
	at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44) ~[craftbukkit.jar:git-Spigot-65e8124-bde2a93]
	... 15 more
Caused by: java.sql.SQLException: No operations allowed after statement closed.
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:964) ~[craftbukkit.jar:git-Spigot-65e8124-bde2a93]
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:897) ~[craftbukkit.jar:git-Spigot-65e8124-bde2a93]
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:886) ~[craftbukkit.jar:git-Spigot-65e8124-bde2a93]
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:860) ~[craftbukkit.jar:git-Spigot-65e8124-bde2a93]
	at com.mysql.jdbc.StatementImpl.checkClosed(StatementImpl.java:442) ~[craftbukkit.jar:git-Spigot-65e8124-bde2a93]
	at com.mysql.jdbc.PreparedStatement.setInternal(PreparedStatement.java:3340) ~[craftbukkit.jar:git-Spigot-65e8124-bde2a93]
	at com.mysql.jdbc.PreparedStatement.setInt(PreparedStatement.java:3302) ~[craftbukkit.jar:git-Spigot-65e8124-bde2a93]
	at com.griefcraft.sql.PhysDB.precache(PhysDB.java:907) ~[?:?]
	at com.griefcraft.modules.admin.AdminPurge.onCommand(AdminPurge.java:77) ~[?:?]
	at com.griefcraft.scripting.ModuleLoader.dispatchEvent(ModuleLoader.java:370) ~[?:?]
	at com.griefcraft.lwc.LWCPlugin.onCommand(LWCPlugin.java:175) ~[?:?]
	at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44) ~[craftbukkit.jar:git-Spigot-65e8124-bde2a93]
	... 15 more

**Comment by megoesrawr** [comment]
It will be fixed in 1.8.8

**Comment by ScuroK** [comment]
@megoesrawr First it seemed to work again after your fix update. but now i got the same errors again. can you pls check it?
