### ISSUE TITLE
Could not pass event EntityDamageEvent to LWC v1.9.4

### ISSUE THREAD

**Issue by mrcoffee1026** [megoesrawr/LWCEntityLocking#43]
Logs as follows, first time I've seen it though, could be a fluke:

```
org.bukkit.event.EventException: null
	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:306) ~[spigot-1.12.2-R0.1-SNAPSHOT.jar:git-Spigot-4bd94dc-fd702e4]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[spigot-1.12.2-R0.1-SNAPSHOT.jar:git-Spigot-4bd94dc-fd702e4]
	at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:500) [spigot-1.12.2-R0.1-SNAPSHOT.jar:git-Spigot-4bd94dc-fd702e4]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:485) [spigot-1.12.2-R0.1-SNAPSHOT.jar:git-Spigot-4bd94dc-fd702e4]
	at org.bukkit.craftbukkit.v1_12_R1.event.CraftEventFactory.callEvent(CraftEventFactory.java:93) [spigot-1.12.2-R0.1-SNAPSHOT.jar:git-Spigot-4bd94dc-fd702e4]
	at org.bukkit.craftbukkit.v1_12_R1.event.CraftEventFactory.callEntityDamageEvent(CraftEventFactory.java:580) [spigot-1.12.2-R0.1-SNAPSHOT.jar:git-Spigot-4bd94dc-fd702e4]
	at org.bukkit.craftbukkit.v1_12_R1.event.CraftEventFactory.handleEntityDamageEvent(CraftEventFactory.java:566) [spigot-1.12.2-R0.1-SNAPSHOT.jar:git-Spigot-4bd94dc-fd702e4]
	at org.bukkit.craftbukkit.v1_12_R1.event.CraftEventFactory.handleLivingEntityDamageEvent(CraftEventFactory.java:612) [spigot-1.12.2-R0.1-SNAPSHOT.jar:git-Spigot-4bd94dc-fd702e4]
	at net.minecraft.server.v1_12_R1.EntityLiving.damageEntity0(EntityLiving.java:1344) [spigot-1.12.2-R0.1-SNAPSHOT.jar:git-Spigot-4bd94dc-fd702e4]
	at net.minecraft.server.v1_12_R1.EntityLiving.damageEntity(EntityLiving.java:868) [spigot-1.12.2-R0.1-SNAPSHOT.jar:git-Spigot-4bd94dc-fd702e4]
	at net.minecraft.server.v1_12_R1.EntityHorseAbstract.damageEntity(EntityHorseAbstract.java:166) [spigot-1.12.2-R0.1-SNAPSHOT.jar:git-Spigot-4bd94dc-fd702e4]
	at net.minecraft.server.v1_12_R1.EntityLiving.Y(EntityLiving.java:210) [spigot-1.12.2-R0.1-SNAPSHOT.jar:git-Spigot-4bd94dc-fd702e4]
	at net.minecraft.server.v1_12_R1.EntityInsentient.Y(EntityInsentient.java:186) [spigot-1.12.2-R0.1-SNAPSHOT.jar:git-Spigot-4bd94dc-fd702e4]
	at net.minecraft.server.v1_12_R1.Entity.B_(Entity.java:320) [spigot-1.12.2-R0.1-SNAPSHOT.jar:git-Spigot-4bd94dc-fd702e4]
	at net.minecraft.server.v1_12_R1.EntityLiving.B_(EntityLiving.java:1871) [spigot-1.12.2-R0.1-SNAPSHOT.jar:git-Spigot-4bd94dc-fd702e4]
	at net.minecraft.server.v1_12_R1.EntityInsentient.B_(EntityInsentient.java:246) [spigot-1.12.2-R0.1-SNAPSHOT.jar:git-Spigot-4bd94dc-fd702e4]
	at net.minecraft.server.v1_12_R1.EntityHorseAbstract.B_(EntityHorseAbstract.java:526) [spigot-1.12.2-R0.1-SNAPSHOT.jar:git-Spigot-4bd94dc-fd702e4]
	at net.minecraft.server.v1_12_R1.World.entityJoinedWorld(World.java:1631) [spigot-1.12.2-R0.1-SNAPSHOT.jar:git-Spigot-4bd94dc-fd702e4]
	at net.minecraft.server.v1_12_R1.World.h(World.java:1601) [spigot-1.12.2-R0.1-SNAPSHOT.jar:git-Spigot-4bd94dc-fd702e4]
	at net.minecraft.server.v1_12_R1.World.tickEntities(World.java:1435) [spigot-1.12.2-R0.1-SNAPSHOT.jar:git-Spigot-4bd94dc-fd702e4]
	at net.minecraft.server.v1_12_R1.WorldServer.tickEntities(WorldServer.java:665) [spigot-1.12.2-R0.1-SNAPSHOT.jar:git-Spigot-4bd94dc-fd702e4]
	at net.minecraft.server.v1_12_R1.MinecraftServer.D(MinecraftServer.java:817) [spigot-1.12.2-R0.1-SNAPSHOT.jar:git-Spigot-4bd94dc-fd702e4]
	at net.minecraft.server.v1_12_R1.DedicatedServer.D(DedicatedServer.java:406) [spigot-1.12.2-R0.1-SNAPSHOT.jar:git-Spigot-4bd94dc-fd702e4]
	at net.minecraft.server.v1_12_R1.MinecraftServer.C(MinecraftServer.java:679) [spigot-1.12.2-R0.1-SNAPSHOT.jar:git-Spigot-4bd94dc-fd702e4]
	at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:577) [spigot-1.12.2-R0.1-SNAPSHOT.jar:git-Spigot-4bd94dc-fd702e4]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_151]
Caused by: com.griefcraft.scripting.ModuleException: java.sql.SQLException: Parameter index out of range (2 > number of parameters, which is 1).
	at com.griefcraft.sql.Database.printException(Database.java:212) ~[EntityLWC.jar:?]
	at com.griefcraft.sql.PhysDB.loadProtection(PhysDB.java:956) ~[EntityLWC.jar:?]
	at com.griefcraft.sql.PhysDB.loadProtection(PhysDB.java:906) ~[EntityLWC.jar:?]
	at com.griefcraft.listeners.LWCPlayerListener.onEntityDamage(LWCPlayerListener.java:214) ~[EntityLWC.jar:?]
	at sun.reflect.GeneratedMethodAccessor101.invoke(Unknown Source) ~[?:?]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_151]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_151]
	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:302) ~[spigot-1.12.2-R0.1-SNAPSHOT.jar:git-Spigot-4bd94dc-fd702e4]
	... 25 more
Caused by: java.sql.SQLException: Parameter index out of range (2 > number of parameters, which is 1).
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:965) ~[spigot-1.12.2-R0.1-SNAPSHOT.jar:git-Spigot-4bd94dc-fd702e4]
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:898) ~[spigot-1.12.2-R0.1-SNAPSHOT.jar:git-Spigot-4bd94dc-fd702e4]
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:887) ~[spigot-1.12.2-R0.1-SNAPSHOT.jar:git-Spigot-4bd94dc-fd702e4]
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:861) ~[spigot-1.12.2-R0.1-SNAPSHOT.jar:git-Spigot-4bd94dc-fd702e4]
	at com.mysql.jdbc.PreparedStatement.checkBounds(PreparedStatement.java:3327) ~[spigot-1.12.2-R0.1-SNAPSHOT.jar:git-Spigot-4bd94dc-fd702e4]
	at com.mysql.jdbc.PreparedStatement.setInternal(PreparedStatement.java:3312) ~[spigot-1.12.2-R0.1-SNAPSHOT.jar:git-Spigot-4bd94dc-fd702e4]
	at com.mysql.jdbc.PreparedStatement.setInternal(PreparedStatement.java:3351) ~[spigot-1.12.2-R0.1-SNAPSHOT.jar:git-Spigot-4bd94dc-fd702e4]
	at com.mysql.jdbc.PreparedStatement.setInt(PreparedStatement.java:3302) ~[spigot-1.12.2-R0.1-SNAPSHOT.jar:git-Spigot-4bd94dc-fd702e4]
	at com.griefcraft.sql.PhysDB.loadProtection(PhysDB.java:944) ~[EntityLWC.jar:?]
	at com.griefcraft.sql.PhysDB.loadProtection(PhysDB.java:906) ~[EntityLWC.jar:?]
	at com.griefcraft.listeners.LWCPlayerListener.onEntityDamage(LWCPlayerListener.java:214) ~[EntityLWC.jar:?]
	at sun.reflect.GeneratedMethodAccessor101.invoke(Unknown Source) ~[?:?]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_151]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_151]
	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:302) ~[spigot-1.12.2-R0.1-SNAPSHOT.jar:git-Spigot-4bd94dc-fd702e4]
	... 25 more
```

**Comment by megoesrawr** [comment]
It will be fixed in 2.0.0 release of LWC which will be soon (hopefully)
