### ISSUE TITLE
Errors on purge and cleanup

### ISSUE THREAD

**Issue by ScuroK** [megoesrawr/LWCEntityLocking#53]
at com.griefcraft.sql.Database.printException(Database.java:211) ~[?:?]
        at com.griefcraft.sql.PhysDB.resolveProtections(PhysDB.java:843) ~[?:?]
        at com.griefcraft.sql.PhysDB.loadProtections(PhysDB.java:1047) ~[?:?]
        ... 8 more
Caused by: java.sql.SQLException: Streaming result set com.mysql.jdbc.RowDataDynamic@4f0f27ac is still active. No statements may be issued when any streaming result sets are open and in use on a given connection. Ensure that you have called .close() on any active streaming result sets before attempting more queries.
        at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:869) ~[spigot.jar:git-Spigot-c3093ef-7e94e65]
        at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:865) ~[spigot.jar:git-Spigot-c3093ef-7e94e65]
        at com.mysql.jdbc.MysqlIO.checkForOutstandingStreamingData(MysqlIO.java:3214) ~[spigot.jar:git-Spigot-c3093ef-7e94e65]
        at com.mysql.jdbc.MysqlIO.sendCommand(MysqlIO.java:2450) ~[spigot.jar:git-Spigot-c3093ef-7e94e65]
        at com.mysql.jdbc.MysqlIO.sqlQueryDirect(MysqlIO.java:2680) ~[spigot.jar:git-Spigot-c3093ef-7e94e65]
        at com.mysql.jdbc.ConnectionImpl.execSQL(ConnectionImpl.java:2484) ~[spigot.jar:git-Spigot-c3093ef-7e94e65]
        at com.mysql.jdbc.PreparedStatement.executeInternal(PreparedStatement.java:1858) ~[spigot.jar:git-Spigot-c3093ef-7e94e65]
        at com.mysql.jdbc.PreparedStatement.executeQuery(PreparedStatement.java:1966) ~[spigot.jar:git-Spigot-c3093ef-7e94e65]
        at com.griefcraft.sql.PhysDB.resolveProtections(PhysDB.java:840) ~[?:?]
        at com.griefcraft.sql.PhysDB.loadProtections(PhysDB.java:1047) ~[?:?]
        ... 8 more
>

**Comment by ScuroK** [comment]
i had to downgrade now it works again. @megoesrawr are you aware of this purge and cleanup issues in version 2?
