### ISSUE TITLE
ChestShop cannot lock chests after update

### ISSUE THREAD

**Issue by DrPanic** [megoesrawr/LWCEntityLocking#56]
After the Update to Version 2.0 we get this error:
```
[15:29:24] [Server thread/ERROR]: Could not pass event ProtectBlockEvent to ChestShop v3.9.1-SNAPSHOT (build 67)
java.lang.NoSuchMethodError: com.griefcraft.sql.PhysDB.registerProtection(ILcom/griefcraft/model/Protection$Type;Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;III)Lcom/griefcraft/model/Protection;
	at com.Acrobot.ChestShop.Plugins.LightweightChestProtection.onBlockProtect(LightweightChestProtection.java:101) ~[?:?]
	at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor459.execute(Unknown Source) ~[?:?]
	at org.bukkit.plugin.EventExecutor$2.execute(EventExecutor.java:70) ~[PaperSpigot-1.12.2-b1342.jar:git-Paper-1342]
	at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:78) ~[PaperSpigot-1.12.2-b1342.jar:git-Paper-1342]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[PaperSpigot-1.12.2-b1342.jar:git-Paper-1342]
	at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:515) ~[PaperSpigot-1.12.2-b1342.jar:git-Paper-1342]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:500) ~[PaperSpigot-1.12.2-b1342.jar:git-Paper-1342]
	at com.Acrobot.ChestShop.ChestShop.callEvent(ChestShop.java:411) ~[?:?]
	at com.Acrobot.ChestShop.Security.protect(Security.java:26) ~[?:?]
	at com.Acrobot.ChestShop.Plugins.LightweightChestProtection.onShopCreation(LightweightChestProtection.java:43) ~[?:?]
	at com.destroystokyo.paper.event.executor.StaticMethodHandleEventExecutor.execute(StaticMethodHandleEventExecutor.java:34) ~[PaperSpigot-1.12.2-b1342.jar:git-Paper-1342]
	at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:78) ~[PaperSpigot-1.12.2-b1342.jar:git-Paper-1342]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[PaperSpigot-1.12.2-b1342.jar:git-Paper-1342]
	at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:515) ~[PaperSpigot-1.12.2-b1342.jar:git-Paper-1342]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:500) ~[PaperSpigot-1.12.2-b1342.jar:git-Paper-1342]
	at com.Acrobot.ChestShop.ChestShop.callEvent(ChestShop.java:411) ~[?:?]
	at com.Acrobot.ChestShop.Listeners.Block.SignCreate.onSignChange(SignCreate.java:46) ~[?:?]
	at com.destroystokyo.paper.event.executor.StaticMethodHandleEventExecutor.execute(StaticMethodHandleEventExecutor.java:34) ~[PaperSpigot-1.12.2-b1342.jar:git-Paper-1342]
	at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:78) ~[PaperSpigot-1.12.2-b1342.jar:git-Paper-1342]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[PaperSpigot-1.12.2-b1342.jar:git-Paper-1342]
	at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:515) ~[PaperSpigot-1.12.2-b1342.jar:git-Paper-1342]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:500) ~[PaperSpigot-1.12.2-b1342.jar:git-Paper-1342]
	at net.minecraft.server.v1_12_R1.PlayerConnection.a(PlayerConnection.java:2226) ~[PaperSpigot-1.12.2-b1342.jar:git-Paper-1342]
	at net.minecraft.server.v1_12_R1.PacketPlayInUpdateSign.a(SourceFile:44) ~[PaperSpigot-1.12.2-b1342.jar:git-Paper-1342]
	at net.minecraft.server.v1_12_R1.PacketPlayInUpdateSign.a(SourceFile:10) ~[PaperSpigot-1.12.2-b1342.jar:git-Paper-1342]
	at net.minecraft.server.v1_12_R1.PlayerConnectionUtils.lambda$ensureMainThread$0(PlayerConnectionUtils.java:14) ~[PaperSpigot-1.12.2-b1342.jar:git-Paper-1342]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:514) [?:?]
	at java.util.concurrent.FutureTask.run(FutureTask.java:264) [?:?]
	at net.minecraft.server.v1_12_R1.SystemUtils.a(SourceFile:46) [PaperSpigot-1.12.2-b1342.jar:git-Paper-1342]
	at net.minecraft.server.v1_12_R1.MinecraftServer.D(MinecraftServer.java:843) [PaperSpigot-1.12.2-b1342.jar:git-Paper-1342]
	at net.minecraft.server.v1_12_R1.DedicatedServer.D(DedicatedServer.java:426) [PaperSpigot-1.12.2-b1342.jar:git-Paper-1342]
	at net.minecraft.server.v1_12_R1.MinecraftServer.C(MinecraftServer.java:767) [PaperSpigot-1.12.2-b1342.jar:git-Paper-1342]
	at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:665) [PaperSpigot-1.12.2-b1342.jar:git-Paper-1342]
	at java.lang.Thread.run(Thread.java:844) [?:?]
[15:29:24] [Craft Scheduler Thread - 37/INFO]: [ChestShop] DrPanic created a shop - 1 Emerald - B 5 - at [esconia] -344, 41, -1834
```

BTW: Can you commit your version 2.0 to github, please? :)

**Comment by DrPanic** [comment]
Thank you. But it doesn't work. The used function use an String for the Block-ID and not an Integer. I will change this with a PR and you can merge this then.
