### ISSUE TITLE
Issue while attempting cleanup on 2.0.1

### ISSUE THREAD

**Issue by takatalvi** [megoesrawr/LWCEntityLocking#58]
Hi, I just updated to the latest version, and got this when I entered the cleanup command:

>lwc admin cleanup
[10:08:55 INFO]: You have: 84583 protections. 
[10:08:55 INFO]: This may take a while depending on how many protections you have
[10:08:55 INFO]: Processing cleanup request now in a separate thread
[10:08:58 INFO]: Exception caught during cleanup: Failed to prepare statement SELECT * FROM lwc_protections WHERE blockName IS NULL
[10:08:58 WARN]: java.lang.RuntimeException: Failed to prepare statement SELECT * FROM lwc_protections WHERE blockName IS NULL
[10:08:58 WARN]: at com.griefcraft.sql.Database.prepare(Database.java:359)
[10:08:58 WARN]: at com.griefcraft.sql.Database.prepare(Database.java:336)
[10:08:58 WARN]: at com.griefcraft.sql.PhysDB.doUpdate1_13_2(PhysDB.java:2203)
[10:08:58 WARN]: at com.griefcraft.sql.PhysDB.load(PhysDB.java:278)
[10:08:58 WARN]: at com.griefcraft.modules.admin.AdminCleanup$Admin_Cleanup_Thread.run(AdminCleanup.java:178)
[10:08:58 WARN]: at java.lang.Thread.run(Thread.java:748)
[10:08:58 WARN]: Caused by: java.util.concurrent.ExecutionException: org.sqlite.SQLiteException: [SQLITE_BUSY] The database file is locked (database is locked)
[10:08:58 WARN]: at com.google.common.util.concurrent.AbstractFuture.getDoneValue(AbstractFuture.java:502)
[10:08:58 WARN]: at com.google.common.util.concurrent.AbstractFuture.get(AbstractFuture.java:461)
[10:08:58 WARN]: at com.google.common.util.concurrent.AbstractFuture$TrustedFuture.get(AbstractFuture.java:78)
[10:08:58 WARN]: at com.google.common.util.concurrent.Uninterruptibles.getUninterruptibly(Uninterruptibles.java:142)
[10:08:58 WARN]: at com.google.common.cache.LocalCache$Segment.getAndRecordStats(LocalCache.java:2461)
[10:08:58 WARN]: at com.google.common.cache.LocalCache$Segment.loadSync(LocalCache.java:2425)
[10:08:58 WARN]: at com.google.common.cache.LocalCache$Segment.lockedGetOrLoad(LocalCache.java:2298)
[10:08:58 WARN]: at com.google.common.cache.LocalCache$Segment.get(LocalCache.java:2211)
[10:08:58 WARN]: at com.google.common.cache.LocalCache.get(LocalCache.java:4154)
[10:08:58 WARN]: at com.google.common.cache.LocalCache$LocalManualCache.get(LocalCache.java:5060)
[10:08:58 WARN]: at com.griefcraft.sql.Database.prepare(Database.java:354)
[10:08:58 WARN]: ... 5 more
[10:08:58 WARN]: Caused by: org.sqlite.SQLiteException: [SQLITE_BUSY] The database file is locked (database is locked)
[10:08:58 WARN]: at org.sqlite.core.DB.newSQLException(DB.java:909)
[10:08:58 WARN]: at org.sqlite.core.DB.newSQLException(DB.java:921)
[10:08:58 WARN]: at org.sqlite.core.DB.throwex(DB.java:886)
[10:08:58 WARN]: at org.sqlite.core.NativeDB.prepare_utf8(Native Method)
[10:08:58 WARN]: at org.sqlite.core.NativeDB.prepare(NativeDB.java:127)
[10:08:58 WARN]: at org.sqlite.core.DB.prepare(DB.java:227)
[10:08:58 WARN]: at org.sqlite.core.CorePreparedStatement.<init>(CorePreparedStatement.java:41)
[10:08:58 WARN]: at org.sqlite.jdbc3.JDBC3PreparedStatement.<init>(JDBC3PreparedStatement.java:30)
[10:08:58 WARN]: at org.sqlite.jdbc4.JDBC4PreparedStatement.<init>(JDBC4PreparedStatement.java:19)
[10:08:58 WARN]: at org.sqlite.jdbc4.JDBC4Connection.prepareStatement(JDBC4Connection.java:48)
[10:08:58 WARN]: at org.sqlite.jdbc3.JDBC3Connection.prepareStatement(JDBC3Connection.java:263)
[10:08:58 WARN]: at org.sqlite.jdbc3.JDBC3Connection.prepareStatement(JDBC3Connection.java:235)
[10:08:58 WARN]: at com.griefcraft.sql.Database.prepareInternal(Database.java:369)
[10:08:58 WARN]: at com.griefcraft.sql.Database.lambda$1(Database.java:354)
[10:08:58 WARN]: at com.google.common.cache.LocalCache$LocalManualCache$1.load(LocalCache.java:5065)
[10:08:58 WARN]: at com.google.common.cache.LocalCache$LoadingValueReference.loadFuture(LocalCache.java:3716)
[10:08:58 WARN]: at com.google.common.cache.LocalCache$Segment.loadSync(LocalCache.java:2424)
[10:08:58 WARN]: ... 10 more

**Comment by takatalvi** [comment]
Update: I just went in-game, creating new locks works normal, although accessing any existing protection will REMOVE it as corrupted. The server is now vacant, so I will replace the DB with a backup I made prior to the update. If that will not work, I am reverting back to 2.0.0 and hope for the best.

**Comment by takatalvi** [comment]
The problem is still present even when I reverted to 2.0.0 and loaded the DB backup. Whenever accessing an existing protection, LWC just removes it as corrupted. Could the issue be related to the queries it runs? I see that on attempted cleanup, it queries * WHERE blockName IS NULL, while in the DB, there is no blockName column, only blockId. Please, provide a solution, we rely on the DB..

**Comment by Tiippex** [comment]
I think #57 has the same problem...

**Comment by takatalvi** [comment]
Reverting back to 1.9.4 solved the problem for now, as #57 stated. However, I believe the DB conversion somehow didn't work as intended in 2.0.0. The database that was used by 2.0.0 did not have the blockName column, while blockId was still populated. Updating the records manually with a CASE statement to fill out blockName according to the Id didn't help.

**Comment by megoesrawr** [comment]
Closed because there is already an issue for it.
