### ISSUE TITLE
Creaturespawn event

### ISSUE THREAD

**Issue by kamziksvk** [megoesrawr/LWCEntityLocking#59]
Hello this erorr started appearing afthe the last update and it is connected with creature spawn event.

https://hastebin.com/rutayinaso.vbs

**Comment by saturnux** [comment]
same error on place an itemframe (autoprotected)

>[Server thread/ERROR]: Could not pass event HangingPlaceEvent to LWC v2.0.1
org.bukkit.event.EventException: null
	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:306) ~[spigot-1.12.jar:git-Spigot-596221b-9a1fc1e]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[spigot-1.12.jar:git-Spigot-596221b-9a1fc1e]
	at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:499) [spigot-1.12.jar:git-Spigot-596221b-9a1fc1e]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:484) [spigot-1.12.jar:git-Spigot-596221b-9a1fc1e]
	at net.minecraft.server.v1_12_R1.ItemHanging.a(ItemHanging.java:33) [spigot-1.12.jar:git-Spigot-596221b-9a1fc1e]
	at net.minecraft.server.v1_12_R1.ItemStack.placeItem(ItemStack.java:166) [spigot-1.12.jar:git-Spigot-596221b-9a1fc1e]
	at net.minecraft.server.v1_12_R1.PlayerInteractManager.a(PlayerInteractManager.java:505) [spigot-1.12.jar:git-Spigot-596221b-9a1fc1e]
	at net.minecraft.server.v1_12_R1.PlayerConnection.a(PlayerConnection.java:944) [spigot-1.12.jar:git-Spigot-596221b-9a1fc1e]
	at net.minecraft.server.v1_12_R1.PacketPlayInUseItem.a(PacketPlayInUseItem.java:37) [spigot-1.12.jar:git-Spigot-596221b-9a1fc1e]
	at net.minecraft.server.v1_12_R1.PacketPlayInUseItem.a(PacketPlayInUseItem.java:1) [spigot-1.12.jar:git-Spigot-596221b-9a1fc1e]
	at net.minecraft.server.v1_12_R1.PlayerConnectionUtils$1.run(SourceFile:13) [spigot-1.12.jar:git-Spigot-596221b-9a1fc1e]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_111]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_111]
	at net.minecraft.server.v1_12_R1.SystemUtils.a(SourceFile:46) [spigot-1.12.jar:git-Spigot-596221b-9a1fc1e]
	at net.minecraft.server.v1_12_R1.MinecraftServer.D(MinecraftServer.java:747) [spigot-1.12.jar:git-Spigot-596221b-9a1fc1e]
	at net.minecraft.server.v1_12_R1.DedicatedServer.D(DedicatedServer.java:405) [spigot-1.12.jar:git-Spigot-596221b-9a1fc1e]
	at net.minecraft.server.v1_12_R1.MinecraftServer.C(MinecraftServer.java:678) [spigot-1.12.jar:git-Spigot-596221b-9a1fc1e]
	at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:576) [spigot-1.12.jar:git-Spigot-596221b-9a1fc1e]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_111]
Caused by: java.lang.ClassCastException: org.bukkit.craftbukkit.v1_12_R1.entity.CraftItemFrame cannot be cast to com.griefcraft.bukkit.EntityBlock
	at com.griefcraft.listeners.LWCEntityListener.entityCreatedByPlayer(LWCEntityListener.java:110) ~[?:?]
	at com.griefcraft.listeners.LWCEntityListener.onHangingPlace(LWCEntityListener.java:74) ~[?:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_111]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_111]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_111]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_111]
	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:302) ~[spigot-1.12.jar:git-Spigot-596221b-9a1fc1e]
	... 18 more

**Comment by good3n** [comment]
+1 Creature spawn event.
https://paste.thezomg.com/56902/52398156/

**Comment by megoesrawr** [comment]
Fixing in newest version.
