### ISSUE TITLE
Internal Error. Notify an admin immediately: PLAYER_INTERACT

### ISSUE THREAD

**Issue by robotnikthingy** [megoesrawr/LWCEntityLocking#9]
I just installed this unofficial version of LWC to replace the old official one. However, a lot of locked chests won't open, and instead give the error in chat:

Internal Error. Notify an admin immediately: PLAYER_INTERACT

heres whats shown in the console

`[16:52:17] [Server thread/WARN]: java.lang.IllegalArgumentException: Invalid UUID string: robotnikthingy
[16:52:17] [Server thread/WARN]:    at java.util.UUID.fromString(UUID.java:194)
[16:52:17] [Server thread/WARN]:    at com.griefcraft.model.Protection.getBukkitOwner(Protection.java:956)
[16:52:17] [Server thread/WARN]:    at com.griefcraft.lwc.LWC.canAccessProtection(LWC.java:777)
[16:52:17] [Server thread/WARN]:    at com.griefcraft.listeners.LWCPlayerListener.onPlayerInteract(LWCPlayerListener.java:647)
[16:52:17] [Server thread/WARN]:    at sun.reflect.GeneratedMethodAccessor174.invoke(Unknown Source)
[16:52:17] [Server thread/WARN]:    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[16:52:17] [Server thread/WARN]:    at java.lang.reflect.Method.invoke(Method.java:498)
[16:52:17] [Server thread/WARN]:    at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:306)
[16:52:17] [Server thread/WARN]:    at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62)
[16:52:17] [Server thread/WARN]:    at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:502)
[16:52:17] [Server thread/WARN]:    at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:487)
[16:52:17] [Server thread/WARN]:    at org.bukkit.craftbukkit.v1_10_R1.event.CraftEventFactory.callPlayerInteractEvent(CraftEventFactory.java:231)
[16:52:17] [Server thread/WARN]:    at net.minecraft.server.v1_10_R1.PlayerInteractManager.a(PlayerInteractManager.java:492)
[16:52:17] [Server thread/WARN]:    at net.minecraft.server.v1_10_R1.PlayerConnection.a(PlayerConnection.java:890)
[16:52:17] [Server thread/WARN]:    at net.minecraft.server.v1_10_R1.PacketPlayInUseItem.a(SourceFile:55)
[16:52:17] [Server thread/WARN]:    at net.minecraft.server.v1_10_R1.PacketPlayInUseItem.a(SourceFile:11)
[16:52:17] [Server thread/WARN]:    at net.minecraft.server.v1_10_R1.PlayerConnectionUtils$1.run(SourceFile:13)
[16:52:17] [Server thread/WARN]:    at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
[16:52:17] [Server thread/WARN]:    at java.util.concurrent.FutureTask.run(FutureTask.java:266)
[16:52:17] [Server thread/WARN]:    at net.minecraft.server.v1_10_R1.SystemUtils.a(SourceFile:45)
[16:52:17] [Server thread/WARN]:    at net.minecraft.server.v1_10_R1.MinecraftServer.D(MinecraftServer.java:732)
[16:52:17] [Server thread/WARN]:    at net.minecraft.server.v1_10_R1.DedicatedServer.D(DedicatedServer.java:400)
[16:52:17] [Server thread/WARN]:    at net.minecraft.server.v1_10_R1.MinecraftServer.C(MinecraftServer.java:668)
[16:52:17] [Server thread/WARN]:    at net.minecraft.server.v1_10_R1.MinecraftServer.run(MinecraftServer.java:567)
[16:52:17] [Server thread/WARN]:    at java.lang.Thread.run(Thread.java:745)`

**Comment by megoesrawr** [comment]
That happens when the SQL has data that isnt right. Like a name instead of UUID.
